# Generated by Django 4.2.7 on 2024-01-12 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('echo9_app', '0003_userprofile_referral_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='inviter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='echo9_app.userprofile'),
        ),
    ]
