# Generated by Django 4.2.7 on 2024-01-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo9_app', '0006_alter_userprofile_referred_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='referred_users',
            field=models.ManyToManyField(blank=True, related_name='referred_by', to='echo9_app.userprofile'),
        ),
    ]
