# Generated by Django 4.2.7 on 2024-01-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo9_app', '0008_userprofile_withdrawal_request_pending_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawalwallet',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='withdrawalwallet',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
