# Generated by Django 4.2.7 on 2024-01-12 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('echo9_app', '0009_rename_timestamp_withdrawalwallet_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='referred_users',
            field=models.ManyToManyField(blank=True, related_name='referred_by', to='echo9_app.userprofile'),
        ),
        migrations.AlterField(
            model_name='withdrawalwallet',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processed', 'Processed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='Running', max_length=20)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('maturity_days', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matured_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='echo9_app.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='investment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_investment', to='echo9_app.investment'),
        ),
    ]
