# Generated by Django 4.2.7 on 2024-01-12 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('echo9_app', '0012_referral_investmentwallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referred_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_given', to='echo9_app.userprofile'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referring_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to='echo9_app.userprofile'),
        ),
    ]
