# Generated by Django 4.2.7 on 2024-01-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo9_app', '0014_alter_investment_status_alter_referral_referred_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='referred_users',
            field=models.ManyToManyField(blank=True, to='echo9_app.userprofile'),
        ),
    ]
