# Generated by Django 4.2.7 on 2024-01-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo9_app', '0018_cointransaction_buy_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='coin_wallet',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
