# Generated by Django 4.2.7 on 2024-01-14 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo9_app', '0019_userprofile_coin_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='cointransaction',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
