# Generated by Django 4.2.7 on 2024-01-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo9_app', '0020_cointransaction_sell_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalwallet',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
