# Generated by Django 4.2.7 on 2024-01-14 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('echo9_app', '0021_alter_withdrawalwallet_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cointransaction',
            name='buy_price',
        ),
        migrations.RemoveField(
            model_name='cointransaction',
            name='sell_price',
        ),
        migrations.AlterField(
            model_name='cointransaction',
            name='transaction_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4),
        ),
        migrations.AlterField(
            model_name='cointransaction',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='echo9_app.userprofile'),
        ),
        migrations.CreateModel(
            name='CoinOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='echo9_app.echocoin')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='echo9_app.userprofile')),
            ],
        ),
    ]
