# Generated by Django 4.2.7 on 2024-01-15 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('echo9_app', '0025_pledgetransaction_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledgetransaction',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buying_pledges', to=settings.AUTH_USER_MODEL, verbose_name='Buyer'),
        ),
        migrations.AlterField(
            model_name='pledgetransaction',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selling_pledges', to=settings.AUTH_USER_MODEL, verbose_name='Seller'),
        ),
    ]
