# Generated by Django 4.2.7 on 2024-01-16 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('echo9_app', '0027_pledge_transaction_delete_pledgetransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_date',
        ),
        migrations.AlterField(
            model_name='pledge',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_transactions', to='echo9_app.userprofile'),
        ),
    ]
