# Generated by Django 4.2.7 on 2024-01-16 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('echo9_app', '0028_remove_transaction_transaction_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_sales', to='echo9_app.userprofile')),
                ('pledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='echo9_app.pledge')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_sales', to='echo9_app.userprofile')),
            ],
        ),
    ]
