# Generated by Django 4.2.7 on 2024-01-16 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('echo9_app', '0029_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='pledge',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='profit',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_bought', to='echo9_app.userprofile'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_sold', to='echo9_app.userprofile'),
        ),
    ]
