# Generated by Django 4.2.7 on 2024-01-16 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('echo9_app', '0030_remove_transaction_pledge_remove_transaction_profit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_sold', to='echo9_app.userprofile'),
        ),
    ]
